Revert "Adds the Moodle 4.4 version of the Ilios Enrollment plugin."
ucsf-ckm/moodle pull request #96
Opened 2024-10-21 16:11 UTC by lbailey-ucsf

Reverts ucsf-education/moodle#89

This commit appears to have caused phpUnit test failures and is being reverted.

2024-10-21 18:44 UTC, ctam requested changes
Please also remove the related lines in the `.gitmodules` file to be complete.
You can also just run `git rm <path-to-submodule>`, and commit.  It used to be a lot more work to do that, but the new git version makes it easier now.
(notify @mirleu and @stopfstedt here, too, on how to properly remove a git submodule.)

2024-10-21 18:46 UTC, ctam commented
Hey, @lbailey-ucsf, what did you change? The tests in the GHA workflow start running again! 🥳

2024-10-21 18:49 UTC, ctam commented
Oh, you created the PR branch here on this repo instead of your own fork, and that's why it got run here. 🙃

2024-10-21 19:26 UTC, lbailey-ucsf commented
@ctam , I do not think it's possible to revert a PR from the fork side. Also, the PR in question, PR #89,  did not originate from my fork. But I'm surprised the revert didn't also revert .gitmodules because that file was as part of the commit associate with PR #89.

2024-10-21 20:02 UTC, lbailey-ucsf commented
@ctam did the GH_PAT expire?

2024-10-22 00:11 UTC, ctam approved these changes
lgtm

2024-10-22 00:49 UTC, merged